version: '3.3'
services:
  iperf3:
    restart: unless-stopped
    container_name: iperf3-server-4001
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
    image: networkstatic/iperf3
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: -s -p 4001
