---
volumes:
  semaphore-mysql:
    driver: local
services:
  mysql:
    container_name: ansiblesemaphore-mysql
    image: docker.io/library/mysql:8.3
    hostname: ansiblesemaphore-mysql
    volumes:
      - /automation/docker/semaphore/semaphore-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=semaphore
      - MYSQL_USER=semaphore
      - MYSQL_PASSWORD=semaphore_pwd
    restart: unless-stopped
    networks: 
      - dockernet
  semaphore:
    container_name: ansiblesemaphore
    image: docker.io/semaphoreui/semaphore:v2.9.75
    user: "0:0"
    ports:
      - 3020:3000
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=semaphore_pwd
      - SEMAPHORE_DB_HOST=ansiblesemaphore-mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=atll0vesPANA
      - SEMAPHORE_ADMIN_NAME=hlayne
      - SEMAPHORE_ADMIN_EMAIL=hlayne@gmail.com
      - SEMAPHORE_ADMIN=hlayne
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=P1nzjCK2qYxiKYogJpK9X1cTav7dn/TLYt4MWXP/ynE=
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
    volumes:
      - /automation/docker/semaphore/inventory/:/inventory:ro
      - /automation/docker/semaphore/authorized-keys/:/authorized-keys:ro
      - /automation/docker/semaphore/config/:/etc/semaphore:rw
    restart: unless-stopped
    depends_on:
      - mysql
    networks: 
      - dockernet
networks: 
  dockernet: 
    external: true
