
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  HOMELAB1:
    style: row
    columns: 6
  HOMELAB2:
    style: row
    columns: 6
  VPS:
    style: row
    columns: 6
  HOMENET:
    style: row
    columns: 6
  CASONA:
   style: row
   columns: 6
  CTECH:
    style: row
    columns: 6
  CPLAB:
    style: row
    columns: 6
  SERVARR:
    style: row
    columns: 6
  HOMESETUP:
    style: row
    columns: 6
#  FWA-TUNNELS:
#    style: row
#    columns: 6
#  FWA-SPEEDTEST:
#    style: row
#    columns: 6
#  FWA-PORTAINER:
#    style: row
#    columns: 6
