services:
  firefox:
    image: kasmweb/chrome:1.14.0
    container_name: chrome
    environment:
      - PUID=1000 #change this to for your settings
      - PGID=1000 #change this to for your settings
      - TZ=America/New_York  #change this to for your location
      - VNC_PW=password
    extra_hosts:
      - host.docker.internal:host-gateway
    networks: 
      - dockernet
    volumes:
      - /automation/docker/firefox/config:/config
    ports:
      - 127.0.0.1:6901:6901
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      - homepage.group=HOMELAB
      - homepage.name=Chrome
      - homepage.icon=chrome.png
      - homepage.href=http://homelab-chrome.laynesystems.com/
      - homepage.description=Web browser
networks: 
  dockernet: 
    external: true