version: "3"
services:
  glances:
    container_name: glances
    image: hlayne/glances:1.0
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    environment:
      - TZ=Americas/New_York
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /automation/docker/glances/data:/glances/conf
    networks: 
      - dockernet
    labels:
      - homepage.group=HOMELAB
      - homepage.name=Glances
      - homepage.icon=glances.png
      - homepage.href=http://homelab-glances.laynesystems.com/
      - homepage.description=Server Stats
networks: 
  dockernet: 
    external: true
