services:
  guacamole:
    image: abesnier/guacamole
    container_name: guacamole
    restart: unless-stopped
    volumes:
      - /automation/docker/guacamole/data:/config
    ports:
      - 127.0.0.1:8080:8080
    networks: 
      - dockernet
networks: 
  dockernet: 
    external: true
