services:
  windows:
    image: dockurr/windows
    container_name: win11-01
    environment:
      VERSION: "win11"
      USERNAME: "wifiops"
      PASSWORD: "atll0vesWIFI"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - /automation/docker/win11-1/data:/shared
    labels:
      - homepage.group=CPLAB
      - homepage.name=win11
      - homepage.icon=windows11.png
      - homepage.href=http://homelab-win1101.laynesystems.com/
      - homepage.description=Windows
    networks: 
      - dockernet
networks: 
  dockernet: 
    external: true
