version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - dockernet
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - eyJhIjoiN2IzYzQ2MmZjMmE0Y2Q0NzcxMWQ1Mjk0ZTJiYTA1MWQiLCJ0IjoiZTFiMWVlMzQtNTRkMC00MWJkLTk2MjYtZTAxZjA0MmVmNDgzIiwicyI6Ik1qUTJNV1V4T0dZdE16aGhPQzAwTlRneUxXRTFaV0l0TnpoaVl6RmpPRGRrWTJNNCJ9

networks:
  dockernet: 
     external: true
