services:
  firefox:
    image: ghcr.io/linuxserver/firefox
    container_name: firefox
    environment:
      - PUID=1000 #change this to for your settings
      - PGID=1000 #change this to for your settings
      - TZ=America/New_York  #change this to for your location
    extra_hosts:
      - host.docker.internal:host-gateway
    networks: 
      - dockernet
    volumes:
      - /automation/docker/firefox/config:/config
    ports:
      - 3010:3000
    shm_size: "1gb"
    restart: unless-stopped
networks: 
  dockernet: 
    external: true
