services:
  putty:
    image: jlesage/putty
    container_name: putty
    environment:
      - PUID=1000 #change this to for your settings
      - PGID=1000 #change this to for your settings
      - TZ=America/New_York  #change this to for your location
    ports:
      - 127.0.0.1:5800:5800
    volumes:
      - "/automation/docker/putty/config:/config:rw"
    networks:
      - dockernet
networks: 
  dockernet:
    external: true 
      
