services:
  db:
    container_name: uvdesk-mysql
    image: mysql:5.7
    volumes:
      - /automation/docker/uvdesk/uvdeskdb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: uvdesk
      MYSQL_ROOT_PASSWORD: perdidohoy
      MYSQL_USER: uvdesk
      MYSQL_PASSWORD: perdidohoy
  uvdesk:
    container_name: uvdesk
    image: nuttcorp/uvdesk:latest
    depends_on:
      - db
    tty: true
    environment:
        MYSQL_USER: uvdesk
        MYSQL_PASSWORD: perdidohoy
        MYSQL_ROOT_PASSWORD: perdidohoy
        MYSQL_DATABASE: uvdesk
        DB_HOST: "uvdesk-mysql"
    ports:
        - 6744:80
    networks: 
      - dockernet
networks: 
  dockernet: 
    external: true
