version: '3.3'
services:
  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server-pgsql
    environment:
      - DB_SERVER_HOST=zabbix-postgres-server
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
      - ZBX_ENABLE_SNMP_TRAPS=true
    volumes:
      - /zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
    restart: unless-stopped
    ports: 
      - 127.0.0.1:10051:10051
    networks:
      - dockernet
networks: 
  dockernet: 
    external: true
