version: '3.3' 
services: 
  zabbix-web-nginx-pgsql: 
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest 
    container_name: zabbix-web-nginx-pgsql 
    environment: 
      - ZBX_SERVER_HOST=zabbix-server-pgsql 
      - DB_SERVER_HOST=zabbix-postgres-server 
      - POSTGRES_USER=zabbix 
      - POSTGRES_PASSWORD=zabbix_pwd 
      - POSTGRES_DB=zabbix 
    restart: unless-stopped 
    ports:  
      - 127.0.0.1:7443:8443 
      - 127.0.0.1:8089:8080 
    networks: 
      - dockernet 
networks:  
  dockernet:  
    external: true 
