services:
  chrome:
    image: kasmweb/chrome:1.16.0
    container_name: chrome
    environment:
      - PUID=1000 #change this to for your settings
      - PGID=1000 #change this to for your settings
      - TZ=America/New_York  #change this to for your location
      - VNC_PW=password
    extra_hosts:
      - host.docker.internal:host-gateway
    networks: 
      - dockernet
    volumes:
      - /automation/docker/chrome/config:/config
    ports:
      - 6910:6901
    shm_size: "1gb"
    restart: unless-stopped
networks: 
  dockernet: 
    external: true
