version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - dockernet
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - eyJhIjoiN2IzYzQ2MmZjMmE0Y2Q0NzcxMWQ1Mjk0ZTJiYTA1MWQiLCJ0IjoiNTJlM2MxMzMtZWMzZS00OGM4LTk5MWEtYjNkMTU2ZWFmODhmIiwicyI6Ik0yRTFaakEyWmpFdE5EQTNOQzAwT0dNMUxXRTNaV0V0TURreU5qUTNOVFE0TURVdyJ9
networks:
  dockernet: 
     external: true
#test
