services:
  glances:
    container_name: glances
    image: nicolargo/glances:3.4.0.5
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    environment:
      - TZ=Americas/New_York
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /automation/docker/glances/data:/glances/conf
    networks: 
      - dockernet
networks: 
  dockernet: 
    external: true
