version: "3"
services:
  database:
    image: mysql
    container_name: wordpress-sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wppassword
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - /automation/docker/wordpress-mysql:/var/lib/mysql
    networks: 
      - dockernet
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - /automation/docker/wordpress:/var/www/html
    networks: 
      dockernet:
networks:
  dockernet:
    external: true
