version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped

    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - eyJhIjoiN2IzYzQ2MmZjMmE0Y2Q0NzcxMWQ1Mjk0ZTJiYTA1MWQiLCJ0IjoiYWMxYjEyNmQtY2NlOC00NTA1LWFjOTItYWVmNWVhNDZjNWJmIiwicyI6Ik5qWTROV1kwT0RRdFl6QmpaaTAwWTJZeExXSmxNVFV0WVRrelpUQmhaamhpWkRjNCJ9
    networks:
      - dockernet
networks:
  dockernet: 
     external: true
